name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pipenv
        pipenv install

    - name: Build decks
      run: |
        pipenv run build

    - name: Generate zips
      run: |
        pipenv run zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/AGAP_v*.zip
          build/AGAP_TTS_v*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
